2022-08-29 20:22:31,414 INFO: Microblog startup [in C:\Users\User\PycharmProjects\flask_miniblog\app\__init__.py:42]
2022-08-29 20:51:41,220 INFO: Microblog startup [in C:\Users\User\PycharmProjects\flask_miniblog\app\__init__.py:42]
2022-08-29 20:52:11,438 INFO: Microblog startup [in C:\Users\User\PycharmProjects\flask_miniblog\app\__init__.py:42]
2022-08-29 22:06:01,431 INFO: Microblog startup [in C:\Users\User\PycharmProjects\flask_miniblog\app\__init__.py:42]
2022-08-29 22:31:47,910 INFO: Microblog startup [in C:\Users\User\PycharmProjects\flask_miniblog\app\__init__.py:42]
2022-08-30 19:40:07,096 INFO: Microblog startup [in C:\Users\User\PycharmProjects\flask_miniblog\app\__init__.py:42]
2022-08-30 20:00:31,127 INFO: Microblog startup [in C:\Users\User\PycharmProjects\flask_miniblog\app\__init__.py:42]
2022-08-30 20:25:10,509 INFO: Microblog startup [in C:\Users\User\PycharmProjects\flask_miniblog\app\__init__.py:42]
2022-08-30 20:25:30,615 ERROR: Exception on /explore [GET] [in C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\flask_miniblog\app\routes.py", line 131, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\User\PycharmProjects\flask_miniblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\User\PycharmProjects\flask_miniblog\app\templates\base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\User\PycharmProjects\flask_miniblog\app\templates\index.html", line 18, in block 'content'
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2022-08-30 20:25:39,216 ERROR: Exception on /index [GET] [in C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\flask_miniblog\app\routes.py", line 30, in index
    return render_template('index.html', title='Home page', form=form, posts=posts)
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\User\PycharmProjects\flask_miniblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\User\PycharmProjects\flask_miniblog\app\templates\base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\User\PycharmProjects\flask_miniblog\app\templates\index.html", line 18, in block 'content'
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2022-08-30 20:25:43,665 ERROR: Exception on /index [GET] [in C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\flask_miniblog\app\routes.py", line 30, in index
    return render_template('index.html', title='Home page', form=form, posts=posts)
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\User\PycharmProjects\flask_miniblog\env\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\User\PycharmProjects\flask_miniblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\User\PycharmProjects\flask_miniblog\app\templates\base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\User\PycharmProjects\flask_miniblog\app\templates\index.html", line 18, in block 'content'
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
